### ISSUE TITLE
Estas declaraciones no deberían ser publicas

### ISSUE THREAD

**Issue by evolentini** [fernandodaniele/CESE-TSSE#3]
Estas definiciones no son necesarias para utilizar la librería, por lo tanto deberían estar en el archivo `.c` y no en el archivo `.h`

https://github.com/fernandodaniele/CESE-TSSE/blob/0fe79423dc4917c8f7edf5b7810e4e5c66bc445f/TPLeds/leds/src/led.h#L6-L9

**Comment by fernandodaniele** [comment]
Se pasaron definiciones a led.c
